title: "Laust Rask"
description: "Nanoscience Graduate from the University of Copenhagen | Quantum Enthusiast"
theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: auto
header_pages:
  - about.md
  - contact.md
  - projects.md
  - publications.md
  - hobbies.md