title: "Laust Rask"
description: "Nanoscience Graduate from the University of Copenhagen | Quantum Enthusiast"
theme: minima

minima:
  skin: auto
header_pages:
  - about.md
  - contact.md
  - projects.md
  - publications.md
  - hobbies.md